### ISSUE TITLE
Updating Coding Style Guidelines

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/documentation#4]
HELP WANTED
Update this page:
https://docs.codebuddies.org/contribution/coding_style.html

The coding style guidelines we want to follow:
- https://standardjs.com/
- https://guide.meteor.com/code-style.html#javascript

**Comment by RobGoelz** [comment]
I can take this!

**Comment by RobGoelz** [comment]
[PR #5 submitted](https://github.com/codebuddies/documentation/pull/5)
